//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPracticalProject.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfPracticalProject.Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to грн/год.
        /// </summary>
        public static string Table_Price_Unit {
            get {
                return ResourceManager.GetString("Table_Price_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string TableCreateEditWindow_CancelButton_Label {
            get {
                return ResourceManager.GetString("TableCreateEditWindow_CancelButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити.
        /// </summary>
        public static string TableCreateEditWindow_CreateButton_Label {
            get {
                return ResourceManager.GetString("TableCreateEditWindow_CreateButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string TableCreateEditWindow_SaveButton_Label {
            get {
                return ResourceManager.GetString("TableCreateEditWindow_SaveButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва Столу :.
        /// </summary>
        public static string TableCreateEditWindow_TableName_Label {
            get {
                return ResourceManager.GetString("TableCreateEditWindow_TableName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип :.
        /// </summary>
        public static string TableCreateEditWindow_TableType_Label {
            get {
                return ResourceManager.GetString("TableCreateEditWindow_TableType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відмінити.
        /// </summary>
        public static string TableDeletionWindow_CancelButton_Label {
            get {
                return ResourceManager.GetString("TableDeletionWindow_CancelButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердити.
        /// </summary>
        public static string TableDeletionWindow_ConfirmButton_Label {
            get {
                return ResourceManager.GetString("TableDeletionWindow_ConfirmButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забронювати.
        /// </summary>
        public static string TableParameters_BookingButton_Label {
            get {
                return ResourceManager.GetString("TableParameters_BookingButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почати таймер.
        /// </summary>
        public static string TableParameters_StartButton_Label {
            get {
                return ResourceManager.GetString("TableParameters_StartButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зупинити таймер.
        /// </summary>
        public static string TableParameters_StopButton_Label {
            get {
                return ResourceManager.GetString("TableParameters_StopButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string TableParameters_TableName_Label {
            get {
                return ResourceManager.GetString("TableParameters_TableName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string TableParameters_TableType_Label {
            get {
                return ResourceManager.GetString("TableParameters_TableType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати.
        /// </summary>
        public static string TablesList_Add_Button {
            get {
                return ResourceManager.GetString("TablesList_Add_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва Столу.
        /// </summary>
        public static string TablesList_ColumnName_TableName {
            get {
                return ResourceManager.GetString("TablesList_ColumnName_TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вартість.
        /// </summary>
        public static string TablesList_ColumnName_TableRate {
            get {
                return ResourceManager.GetString("TablesList_ColumnName_TableRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string TablesList_ColumnName_TableStatus {
            get {
                return ResourceManager.GetString("TablesList_ColumnName_TableStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string TablesList_ColumnName_TableType {
            get {
                return ResourceManager.GetString("TablesList_ColumnName_TableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string TablesList_Delete_Button {
            get {
                return ResourceManager.GetString("TablesList_Delete_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Змінити.
        /// </summary>
        public static string TablesList_Edit_Button {
            get {
                return ResourceManager.GetString("TablesList_Edit_Button", resourceCulture);
            }
        }
    }
}
